version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kenyan_payroll
      POSTGRES_USER: payroll_user
      POSTGRES_PASSWORD: payroll_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payroll_user -d kenyan_payroll"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Web Application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-for-development
      - DATABASE_URL=postgresql://payroll_user:payroll_password@db:5432/kenyan_payroll
      - DJANGO_SETTINGS_MODULE=payroll.settings.production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - payroll_data:/data
    command: ["/app/docker-entrypoint.sh"]
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  payroll_data:
