[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc", "pkg-config", "cairo", "pango", "gdk-pixbuf", "libffi", "shared-mime-info"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "gunicorn payroll.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
