services:
  - type: web
    name: kenyan-payroll-system
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    disk:
      name: kenyan-payroll-data
      mountPath: /data
      sizeGB: 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: payroll.settings.production
      - key: DATABASE_URL
        value: postgresql://payroll_user:1wvyisD4gqJwQfXm6zqZBvWkmRsxa4LS@dpg-d1l5h5p5pdvs73bhvcl0-a.oregon-postgres.render.com/payroll_db_u6tb
      - key: ALLOWED_HOSTS
        value: kenyan-payroll-system.onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://kenyan-payroll-system.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: tidings@outlook.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "@PayrollAdmin2025!"
