services:
  - type: web
    name: kenyan-payroll-system
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
      gunicorn payroll.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: zbk3HW6l2TLXtzZRslzrgW5M282yIDVA14ps44mPp6Aq8rCgAJFjre4hPPPC6mpbAJo
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: payroll.settings.production
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: tidings@outlook.com
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DATABASE_URL
        value: postgresql://payroll_user:1wvyisD4gqJwQfXm6zqZBvWkmRsxa4LS@dpg-d1l5h5p5pdvs73bhvcl0-a.oregon-postgres.render.com/payroll_db_u6tb

  - type: pserv
    name: kenyan-payroll-db
    env: postgresql
    plan: starter
    databaseName: payroll_db
    user: payroll_user
