# Generated by Django 3.1.14 on 2025-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='nhif_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='shif_number',
            field=models.CharField(blank=True, help_text='SHIF membership number (Social Health Insurance Fund)', max_length=20),
        ),
    ]
