# Generated by Django 3.1.14 on 2025-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_nhif_to_shif'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, help_text='Kenyan National ID number (8 digits)', max_length=8, null=True, unique=True),
        ),
    ]
