# Generated by Django 3.1.14 on 2025-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_add_ugatuzi_and_casual_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
