# Generated by Django 4.2.7 on 2025-07-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_make_statutory_fields_optional'),
        ('employees', '0013_auto_20250705_0544'),
    ]

    operations = [
    ]
