# Generated by Django 4.2.7 on 2025-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_restore_logo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.CharField(blank=True, help_text='Logo path - temporarily disabled for Python 3.13 compatibility', max_length=255, null=True),
        ),
    ]
