# Generated by Django 4.2.7 on 2025-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employee_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basic monthly salary in KES', max_digits=12, null=True),
        ),
    ]
