# Generated by Django 3.1.14 on 2025-07-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statutory_deductions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NHIFRate',
        ),
    ]
