name: Generate Django SECRET_KEY

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      environment:
        description: 'Environment (production/staging)'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  generate-secret-key:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Django
      run: |
        pip install django
        
    - name: Generate SECRET_KEY
      id: generate-key
      run: |
        SECRET_KEY=$(python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())")
        echo "Generated SECRET_KEY for ${{ github.event.inputs.environment }}"
        echo "::add-mask::$SECRET_KEY"
        echo "secret_key=$SECRET_KEY" >> $GITHUB_OUTPUT
        
    - name: Display Instructions
      run: |
        echo "🔐 SECRET_KEY Generated Successfully!"
        echo "=================================="
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Next Steps:"
        echo "1. Copy the masked SECRET_KEY from the logs above"
        echo "2. Add it to your deployment platform:"
        echo "   - Render: Environment Variables"
        echo "   - Vercel: Environment Variables"
        echo "   - Heroku: Config Vars"
        echo "3. Use key: SECRET_KEY"
        echo "4. NEVER commit this key to version control"
        echo ""
        echo "⚠️  SECURITY NOTE:"
        echo "This key is masked in logs for security."
        echo "Only authorized users can see the actual value."
        
    - name: Save to GitHub Secrets (Optional)
      if: github.event.inputs.environment == 'production'
      run: |
        echo "To save this as a GitHub Secret:"
        echo "1. Go to Settings → Secrets and variables → Actions"
        echo "2. Click 'New repository secret'"
        echo "3. Name: DJANGO_SECRET_KEY_PROD"
        echo "4. Value: [Copy from masked output above]"
