# Generated by Django 3.1.14 on 2025-07-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsummary',
            name='total_nhif',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='nhif_contribution',
        ),
    ]
